# Generated by Django 6.0.4 on 2026-08-31 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название лагеря')),
            ],
            options={
                'verbose_name': 'Лагерь',
                'verbose_name_plural': 'Лагеря',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_year', models.PositiveSmallIntegerField(verbose_name='Год рождения')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Родитель')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя')),
                ('certificate', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Справка (фото)')),
                ('certificate_note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к справке')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('trial', 'Пробное (2 недели)'), ('archived', 'Архив'), ('lost', 'Потерянный')], default='active', max_length=10, verbose_name='Статус')),
                ('trial_from', models.DateField(blank=True, null=True, verbose_name='Начало пробного периода')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('is_internal', models.BooleanField(default=True, help_text='Внутриклубные итоги попадают в карточку автоматически', verbose_name='Внутриклубные')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Событие журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.camp', verbose_name='лагерь')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_stays', to='crm.child', verbose_name='ребёнок')),
            ],
            options={
                'verbose_name': 'Поездка в лагерь',
                'verbose_name_plural': 'Лагеря (поездки)',
            },
        ),
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Снаряд')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparatus', to='crm.competition', verbose_name='соревнование')),
            ],
            options={
                'verbose_name': 'Снаряд',
                'verbose_name_plural': 'Снаряды',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Внутри категории считается место', max_length=100, verbose_name='Категория/группа')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Выполняемый разряд')),
                ('place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='crm.child', verbose_name='ребёнок')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='crm.competition', verbose_name='соревнование')),
            ],
            options={
                'verbose_name': 'Итог соревнования',
                'verbose_name_plural': 'Итоги соревнований',
            },
        ),
        migrations.CreateModel(
            name='ApparatusScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Баллы')),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.apparatus', verbose_name='снаряд')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='crm.competitionentry', verbose_name='итог')),
            ],
            options={
                'verbose_name': 'Балл за снаряд',
                'verbose_name_plural': 'Баллы за снаряды',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назначение')),
                ('category', models.CharField(choices=[('household', 'Бытовые товары'), ('equipment', 'Инвентарь'), ('repair', 'Ремонт'), ('other', 'Другое')], default='household', max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('receipt', models.FileField(blank=True, upload_to='expense_receipts/', verbose_name='Чек')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.group', verbose_name='группа'),
        ),
        migrations.CreateModel(
            name='ManagerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Пусто — видна всем админам', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача менеджеру',
                'verbose_name_plural': 'Задачи менеджерам',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', unique=True, verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цель, ₽')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='установил')),
            ],
            options={
                'verbose_name': 'Цель по выручке',
                'verbose_name_plural': 'Цели по выручке',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность, мин')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='crm.group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Слот графика',
                'verbose_name_plural': 'Графики групп',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='schedule',
            field=models.ManyToManyField(blank=True, help_text='Пусто — ребёнок ходит по графику группы', to='crm.scheduleslot', verbose_name='личный график'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', '✅ Посещение'), ('absent', '🟥 Пропуск'), ('excused', 'Пропуск по уважительной (сдвигает окончание)'), ('frozen', '🟦 Заморозка'), ('vacation', '🟨 Отпуск')], default='present', max_length=10, verbose_name='Отметка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crm.child', verbose_name='ребёнок')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.scheduleslot', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Рядовой админ'), ('senior', 'Старший админ'), ('boss', 'Начальник')], default='manager', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('sessions_total', models.PositiveSmallIntegerField(default=8, verbose_name='Занятий в абонементе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('promo', models.CharField(blank=True, max_length=100, verbose_name='Акция / промо')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.child', verbose_name='ребёнок')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ('-end_date',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.child', verbose_name='ребёнок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='принял')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.subscription', verbose_name='абонемент')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SalaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выплачено, ₽')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='crm.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Выплата ЗП',
                'verbose_name_plural': 'ЗП тренеров',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='crm.trainer', verbose_name='тренер'),
        ),
        migrations.CreateModel(
            name='ChildRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('rank', models.CharField(max_length=50, verbose_name='Разряд')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='crm.child', verbose_name='ребёнок')),
            ],
            options={
                'verbose_name': 'Разряд',
                'verbose_name_plural': 'Разряды по годам',
                'unique_together': {('child', 'year')},
            },
        ),
        migrations.AddConstraint(
            model_name='competitionentry',
            constraint=models.UniqueConstraint(fields=('child', 'competition', 'category'), name='unique_child_competition_category'),
        ),
        migrations.AddConstraint(
            model_name='apparatusscore',
            constraint=models.UniqueConstraint(fields=('entry', 'apparatus'), name='unique_entry_apparatus'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('child', 'date', 'slot'), name='one_mark_per_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='salarypayout',
            unique_together={('trainer', 'month')},
        ),
    ]
