# Generated by Django 6.0.4 on 2026-09-01 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название филиала')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, ₽')),
                ('sessions_total', models.PositiveSmallIntegerField(default=8, verbose_name='Количество занятий')),
                ('duration_days', models.PositiveSmallIntegerField(default=30, verbose_name='Срок, дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начислено за занятие в долг, ₽'),
        ),
        migrations.AddField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='group',
            name='single_session_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Разовое занятие / занятие в долг, ₽'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='shift_anchor',
            field=models.DateField(blank=True, null=True, verbose_name='Первый рабочий день смены 2/2'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действует'),
        ),
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='crm.branch', verbose_name='филиал'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='crm.branch', verbose_name='филиал'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=220, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('age_text', models.CharField(blank=True, max_length=30, verbose_name='Возраст')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('trial_at', models.DateTimeField(blank=True, null=True, verbose_name='Пробное занятие')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались'), ('qualified', 'Подходит'), ('lost', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('imported_from_ad', models.BooleanField(default=False, verbose_name='Автоматически из рекламы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.child', verbose_name='карточка спортсмена')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.group', verbose_name='группа')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Newcomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=220, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('age_text', models.CharField(blank=True, max_length=30, verbose_name='Возраст')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('trial_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время пробного')),
                ('attended', models.BooleanField(default=False, verbose_name='Был на пробном')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил')),
                ('lesson_cancelled', models.BooleanField(default=False, verbose_name='Занятие отменено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий / перенос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_newcomer', to='crm.child', verbose_name='карточка спортсмена')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomers', to='crm.group', verbose_name='группа')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomers', to='crm.lead', verbose_name='исходная заявка')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomers', to='crm.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Новичок',
                'verbose_name_plural': 'Новички',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Напоминание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('remind_at', models.DateTimeField(verbose_name='Дата и время')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('visible_to_all', models.BooleanField(default=False, verbose_name='Видно всей команде')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ('is_done', 'remind_at'),
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='crm.tariff', verbose_name='тариф'),
        ),
    ]
