# Generated by Django 6.0.4 on 2026-09-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_branch_tariff_attendance_charge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='archived_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ухода/архива'),
        ),
        migrations.AddField(
            model_name='group',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='Ставка за посещение, ₽'),
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('title', models.CharField(max_length=200, verbose_name='Назначение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_adjustments', to='crm.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Строка ЗП',
                'verbose_name_plural': 'Ручные строки ЗП',
            },
        ),
    ]
